import { DEFAULT_LANGUAGE } from "./voiceConfig.js";

/**
 * Page String Assets
 * 
 * Centralized location for all page text content in multiple languages.
 * This ensures consistency across Profile, Transactions, Reminders, Beneficiaries, DeviceBinding, and SignInHelp pages.
 */

export const PAGE_STRINGS = {
  "en-IN": {
    profile: {
      loggedInAs: "Logged in as",
      bankingCustomer: "banking customer",
      customerId: "Customer ID:",
      voiceSessionSecured: "Voice session secured",
      voiceSessionUnsecured: "Voice session unsecured",
      voiceModeOff: "Voice mode off",
      voiceMode: "Voice mode",
      addVoiceToAccount: "Add voice to account",
      addVoicePrompt: "Would you like to add voice authentication to your account for secure banking?",
      addVoicePromptDescription: "Adding voice to your account will enable secure voice-based login and enhance your banking security.",
      forceLogoutTitle: "Device binding revoked",
      forceLogoutMessage: "Your device binding has been revoked. For security reasons, you will be logged out of your account.",
      forceLogoutDescription: "Please log in again to continue using the banking services.",
      okay: "Okay",
      cancel: "Cancel",
      accountSnapshot: "Account snapshot",
      sessionInsights: "Session insights",
      quickActions: "Quick actions",
      lastVoiceLogin: "Last voice login",
      nextReminder: "Next reminder",
      noRecentLogin: "No recent login recorded",
      noRemindersConfigured: "No reminders configured",
      checkBalances: "Check balances",
      makeTransfer: "Make a transfer",
      reviewTransactions: "Review transactions",
      manageReminders: "Manage reminders",
      beneficiaries: "Beneficiaries",
      trustedDevices: "Trusted devices",
      balanceEnquiry: "Balance enquiry",
      account: "Account",
      viewBalance: "View balance",
      checking: "Checking…",
      ledgerBalance: "Ledger balance:",
      availableBalance: "Available balance:",
      status: "Status:",
      internalTransfer: "Internal transfer",
      fromAccount: "From account",
      destinationAccountNumber: "Destination account number",
      savedBeneficiary: "Saved beneficiary (optional)",
      selectBeneficiary: "Select beneficiary",
      amount: "Amount (INR)",
      remarks: "Remarks",
      optionalNarration: "Optional narration",
      initiateTransfer: "Initiate transfer",
      processing: "Processing…",
      transferInitiated: "Transfer initiated successfully.",
      selectSourceAccount: "Select a source account.",
      enterDestinationAccount: "Enter a destination account number.",
      enterValidAmount: "Enter a valid transfer amount.",
      recentTransactions: "Recent transactions",
      fetchingTransactions: "Fetching transactions…",
      selectAccountToView: "Select an account above to view the latest five transactions.",
      viewAllTransactions: "View all transactions",
      reminders: "Reminders",
      type: "Type",
      remindAt: "Remind at",
      message: "Message",
      linkedAccount: "Linked account",
      none: "None",
      channel: "Channel",
      recurrenceRule: "Recurrence rule",
      optionalRrule: "Optional RFC 5545 RRULE",
      createReminder: "Create reminder",
      creating: "Creating…",
      reminderCreated: "Reminder created successfully.",
      noRemindersYet: "No reminders configured yet.",
      viewAllReminders: "View all reminders",
      markSent: "Mark sent",
      beneficiariesTitle: "Beneficiaries",
      noBeneficiariesYet: "No beneficiaries added yet. Add one to speed up transfers.",
      viewAllBeneficiaries: "View all beneficiaries",
      lastUsed: "Last used",
      deviceBinding: {
        title: "Trusted devices",
        noDevices: "No trusted devices found. Add this device to enjoy voice + device binding.",
        loading: "Loading device bindings…",
        lastVerified: "Last verified:",
        never: "Never",
        revoke: "Revoke",
        revoked: "Revoked",
        bindDevice: "Bind this device",
        deviceLabel: "Device label",
        deviceLabelPlaceholder: "e.g., Ananya's Redmi Note",
        voicePassphrase: "Voice passphrase",
        speakPassphrase: "Speak one of the passphrases below during verification:",
        recordVoiceSample: "Record voice sample",
        stopRecording: "Stop recording",
        deviceFingerprint: "Device fingerprint (hashed):",
        bindingDevice: "Binding device…",
        deviceBound: "Device and voice passphrase registered successfully.",
        deviceRevoked: "Device binding revoked successfully.",
        pleaseRecord: "Please record the passphrase",
        beforeBinding: "before binding.",
        manageDeviceBinding: "Manage device & voice binding",
        forSecureBanking: "For secure banking, please bind this device and verify your voice.",
        completeVoiceEnrollment: "Complete voice signature enrollment to finish device binding.",
        refreshVoiceSignature: "Please refresh your voice signature to keep this device trusted.",
        speakPassphraseLabel: "Speak the passphrase:",
        sessionReplacementRequired: "Voice registered successfully. Please log out and sign in again with voice to activate voice authentication.",
        logoutRequired: "You are logging out. This was your only trusted device. Please sign in again to continue.",
        logoutDueToDeviceChange: "Your device binding has been changed from password to voice authentication. For security reasons, you need to log out and sign in again with voice authentication.",
        voiceBindingReplaced: "You have updated your voice binding. For security reasons, you need to log out and sign in again with your new voice sample.",
      },
      logOut: "Log out",
      back: "Back",
      sessionExpired: "Your session expired due to inactivity. Please sign in again.",
      loadingAccountDetails: "Loading account details…",
      showingAccounts: "Showing 5 of",
      accounts: "accounts.",
      hide: "Hide",
      show: "Show",
      debitCards: "Debit cards",
      creditCards: "Credit cards",
      available: "Available",
    },
    transactions: {
      title: "Complete transaction history",
      accounts: "Accounts",
      selectAccount: "Select account",
      currentBalance: "Current balance:",
      sessionExpired: "Your session expired due to inactivity. Please sign in again.",
      transactions: "Transactions",
      noTransactionsFound: "No transactions found for this account.",
      fetchingTransactions: "Fetching transactions…",
      reference: "Reference:",
      downloadStatement: "Download account statement",
      fromDate: "From date",
      toDate: "To date",
      downloadStatementButton: "Download statement",
      preparing: "Preparing…",
      selectAccountToDownload: "Select an account to download a statement.",
      chooseBothDates: "Choose both from and to dates.",
      startDateBeforeEnd: "The start date must be before the end date.",
      invalidDateRange: "Invalid date range provided.",
      statementDownloaded: "Statement downloaded with",
      transaction: "transaction(s).",
      mostRecent: "Statement downloaded with the most recent",
      transactionsLimit: "transactions. For older entries, please download another period.",
      unableToDownload: "Unable to download statement.",
      rbiGuidelines: "As per RBI guidelines, digital statements include up to 500 transactions. Please shorten the date range and try again.",
      back: "Back",
    },
    reminders: {
      title: "All reminders",
      reminders: "Reminders",
      loading: "Loading reminders…",
      noRemindersFound: "No reminders found.",
      markSent: "Mark sent",
      back: "Back",
    },
    beneficiaries: {
      title: "Manage beneficiaries",
      subtitle: "RBI mandates a verified beneficiary list before high-value transfers. Add trusted recipients here so that future payments are quicker and safer.",
      backToPrevious: "← Back to previous page",
      addNewBeneficiary: "Add a new beneficiary",
      beneficiaryName: "Beneficiary name",
      beneficiaryNamePlaceholder: "e.g., Ramesh Kumar",
      accountNumber: "Account number",
      accountNumberPlaceholder: "Enter exact account number",
      bankName: "Bank name",
      bankNamePlaceholder: "Sun National Bank",
      ifsc: "IFSC (optional)",
      ifscPlaceholder: "SUNB0001HYD",
      addBeneficiary: "Add beneficiary",
      adding: "Adding…",
      beneficiaryAdded: "Beneficiary added successfully.",
      provideNameAndAccount: "Please provide a beneficiary name and account number.",
      savedBeneficiaries: "Saved beneficiaries",
      loading: "Loading beneficiaries…",
      noBeneficiariesYet: "No beneficiaries added yet.",
      addedOn: "Added on",
      remove: "Remove",
      removeConfirm: "This will disable the beneficiary immediately. Do you want to continue?",
      productionNote: "Production deployments will enforce a cooling period and OTP confirmation before a beneficiary becomes active.",
      logOut: "Log out",
    },
    deviceBinding: {
      title: "Manage trusted devices and voice binding",
      trustedDevices: "Trusted devices",
      loading: "Loading device bindings…",
      noDevices: "No trusted devices found. Add this device to enjoy voice + device binding.",
      lastVerified: "Last verified:",
      never: "Never",
      revoke: "Revoke",
      revoked: "Revoked",
      bindDevice: "Bind this device",
      description: "Voice + device binding pairs your voice signature with this device as per RBI's risk-based authentication guidance. Provide a friendly label, then record yourself speaking the passphrase so we can secure this device.",
      deviceLabel: "Device label",
      deviceLabelPlaceholder: "e.g., Ananya's Redmi Note",
      voicePassphrase: "Voice passphrase",
      speakPassphrase: "Speak one of the passphrases below during verification:",
      recordVoiceSample: "Record voice sample",
      stopRecording: "Stop recording",
      deviceFingerprint: "Device fingerprint (hashed):",
      bindingDevice: "Binding device…",
      deviceBound: "Device and voice passphrase registered successfully.",
      deviceRevoked: "Device binding revoked successfully.",
      pleaseRecord: "Please record the passphrase",
      beforeBinding: "before binding.",
      sessionExpired: "Your session expired. Please sign in again to manage trusted devices.",
      back: "Back",
    },
    signInHelp: {
      title: "Need help signing in?",
      subtitle: "Follow these quick steps to access your Sun National Bank profile using either your password or voice with the audio OTP safeguard.",
      passwordOtp: "Password + OTP",
      step1: "Enter your customer User ID exactly as issued by the bank.",
      step2: "Type your password and press",
      step3: "The system validates your credentials and then prompts for the one-time password.",
      step4: "Enter the prototype OTP",
      step4Note: "(production will use SMS/email/WhatsApp).",
      step5: "Submit to finish signing in. Incorrect entries reset the OTP step for security.",
      voiceLoginOtp: "Voice login + OTP",
      voiceStep1: "Select the",
      voiceStep1Bold: "Voice",
      voiceStep1End: "tab on the login screen.",
      voiceStep2: "For first-time users, record the passphrase \"Sun Bank mera saathi, har kadam surakshit banking ka vaada\" twice to enrol your voice signature.",
      voiceStep3: "Returning users can speak any clear phrase. Watch the audio meter to stay within the 7-second capture window.",
      voiceStep4: "After the voice check passes, enter the OTP",
      voiceStep4End: "to complete login.",
      voiceTip: "Tip: Record from a quiet space and keep the microphone 10–15 cm away for best matching accuracy.",
      stillCantSignIn: "Still can't sign in?",
      usePasswordMode: "Use the password mode if your voice sample is unavailable.",
      clearBrowserCache: "Clear your browser cache or retry in a private window to refresh device bindings.",
      enableMicrophone: "Ensure your microphone permissions are enabled for this site.",
      contactSupport: "Contact branch support to reset your password or revoke suspicious device bindings.",
      goBack: "Go back",
      returnToLogin: "Return to login",
      logIn: "Log in",
    },
    chat: {
      handsFreeEnabled: "Hands-free enabled",
      backToProfile: "← Back to Profile",
      logOut: "Log out",
      uploadQRCode: "Upload QR Code",
      assistantSpeaking: "Assistant is speaking...",
      wasThisHelpful: "Was this helpful?",
      goodResponse: "Good response",
      badResponse: "Bad response",
      downloadStatement: "Download Statement",
      downloadStatementTitle: "Download account statement as CSV",
    },
  },
  "hi-IN": {
    profile: {
      loggedInAs: "लॉग इन किया गया",
      bankingCustomer: "बैंकिंग ग्राहक",
      customerId: "ग्राहक आईडी:",
      voiceSessionSecured: "आवाज़ सत्र सुरक्षित",
      voiceSessionUnsecured: "आवाज़ सत्र असुरक्षित",
      voiceModeOff: "वॉइस मोड बंद",
      voiceMode: "वॉइस मोड",
      addVoiceToAccount: "खाते में आवाज़ जोड़ें",
      addVoicePrompt: "क्या आप सुरक्षित बैंकिंग के लिए अपने खाते में आवाज़ प्रमाणीकरण जोड़ना चाहेंगे?",
      addVoicePromptDescription: "अपने खाते में आवाज़ जोड़ने से सुरक्षित आवाज़-आधारित लॉगिन सक्षम होगा और आपकी बैंकिंग सुरक्षा बढ़ेगी।",
      forceLogoutTitle: "उपकरण बाइंडिंग रद्द की गई",
      forceLogoutMessage: "आपकी उपकरण बाइंडिंग रद्द कर दी गई है। सुरक्षा कारणों से, आपको अपने खाते से लॉग आउट कर दिया जाएगा।",
      forceLogoutDescription: "कृपया बैंकिंग सेवाओं का उपयोग जारी रखने के लिए फिर से लॉग इन करें।",
      okay: "ठीक है",
      cancel: "रद्द करें",
      accountSnapshot: "खाता स्नैपशॉट",
      sessionInsights: "सत्र अंतर्दृष्टि",
      quickActions: "त्वरित कार्य",
      lastVoiceLogin: "अंतिम आवाज़ लॉगिन",
      nextReminder: "अगली अनुस्मारक",
      noRecentLogin: "कोई हालिया लॉगिन दर्ज नहीं किया गया",
      noRemindersConfigured: "कोई अनुस्मारक कॉन्फ़िगर नहीं किया गया",
      checkBalances: "शेष राशि जांचें",
      makeTransfer: "ट्रांसफर करें",
      reviewTransactions: "लेनदेन की समीक्षा करें",
      manageReminders: "अनुस्मारक प्रबंधित करें",
      beneficiaries: "लाभार्थी",
      trustedDevices: "विश्वसनीय उपकरण",
      balanceEnquiry: "शेष राशि पूछताछ",
      account: "खाता",
      viewBalance: "शेष राशि देखें",
      checking: "जांच रहे हैं…",
      ledgerBalance: "लेजर शेष राशि:",
      availableBalance: "उपलब्ध शेष राशि:",
      status: "स्थिति:",
      internalTransfer: "आंतरिक ट्रांसफर",
      fromAccount: "खाते से",
      destinationAccountNumber: "गंतव्य खाता संख्या",
      savedBeneficiary: "सहेजा गया लाभार्थी (वैकल्पिक)",
      selectBeneficiary: "लाभार्थी चुनें",
      amount: "राशि (INR)",
      remarks: "टिप्पणियाँ",
      optionalNarration: "वैकल्पिक वर्णन",
      initiateTransfer: "ट्रांसफर शुरू करें",
      processing: "प्रसंस्करण कर रहे हैं…",
      transferInitiated: "ट्रांसफर सफलतापूर्वक शुरू किया गया।",
      selectSourceAccount: "एक स्रोत खाता चुनें।",
      enterDestinationAccount: "एक गंतव्य खाता संख्या दर्ज करें।",
      enterValidAmount: "एक वैध ट्रांसफर राशि दर्ज करें।",
      recentTransactions: "हालिया लेनदेन",
      fetchingTransactions: "लेनदेन प्राप्त कर रहे हैं…",
      selectAccountToView: "नवीनतम पांच लेनदेन देखने के लिए ऊपर एक खाता चुनें।",
      viewAllTransactions: "सभी लेनदेन देखें",
      reminders: "अनुस्मारक",
      type: "प्रकार",
      remindAt: "याद दिलाएं",
      message: "संदेश",
      linkedAccount: "लिंक किया गया खाता",
      none: "कोई नहीं",
      channel: "चैनल",
      recurrenceRule: "पुनरावृत्ति नियम",
      optionalRrule: "वैकल्पिक RFC 5545 RRULE",
      createReminder: "अनुस्मारक बनाएं",
      creating: "बना रहे हैं…",
      reminderCreated: "अनुस्मारक सफलतापूर्वक बनाया गया।",
      noRemindersYet: "अभी तक कोई अनुस्मारक कॉन्फ़िगर नहीं किया गया।",
      viewAllReminders: "सभी अनुस्मारक देखें",
      markSent: "भेजा गया चिह्नित करें",
      beneficiariesTitle: "लाभार्थी",
      noBeneficiariesYet: "अभी तक कोई लाभार्थी नहीं जोड़ा गया। ट्रांसफर को तेज़ करने के लिए एक जोड़ें।",
      viewAllBeneficiaries: "सभी लाभार्थी देखें",
      lastUsed: "अंतिम उपयोग",
      deviceBinding: {
        title: "विश्वसनीय उपकरण",
        noDevices: "कोई विश्वसनीय उपकरण नहीं मिला। आवाज़ + उपकरण बाइंडिंग का आनंद लेने के लिए इस उपकरण को जोड़ें।",
        loading: "उपकरण बाइंडिंग लोड कर रहे हैं…",
        lastVerified: "अंतिम सत्यापित:",
        never: "कभी नहीं",
        revoke: "रद्द करें",
        revoked: "रद्द किया गया",
        bindDevice: "इस उपकरण को बाइंड करें",
        deviceLabel: "उपकरण लेबल",
        deviceLabelPlaceholder: "उदा., अनन्या का रेडमी नोट",
        voicePassphrase: "आवाज़ पासफ़्रेज़",
        speakPassphrase: "सत्यापन के दौरान नीचे दिए गए पासफ़्रेज़ में से एक बोलें:",
        recordVoiceSample: "आवाज़ का नमूना रिकॉर्ड करें",
        stopRecording: "रिकॉर्डिंग रोकें",
        deviceFingerprint: "उपकरण फिंगरप्रिंट (हैश किया गया):",
        bindingDevice: "उपकरण बाइंड कर रहे हैं…",
        deviceBound: "उपकरण और आवाज़ पासफ़्रेज़ सफलतापूर्वक पंजीकृत किया गया।",
        deviceRevoked: "उपकरण बाइंडिंग सफलतापूर्वक रद्द की गई।",
        pleaseRecord: "कृपया पासफ़्रेज़ रिकॉर्ड करें",
        beforeBinding: "बाइंडिंग से पहले।",
        manageDeviceBinding: "उपकरण और आवाज़ बाइंडिंग प्रबंधित करें",
        forSecureBanking: "सुरक्षित बैंकिंग के लिए, कृपया इस उपकरण को बाइंड करें और अपनी आवाज़ सत्यापित करें।",
        completeVoiceEnrollment: "उपकरण बाइंडिंग समाप्त करने के लिए आवाज़ हस्ताक्षर पंजीकरण पूरा करें।",
        refreshVoiceSignature: "इस उपकरण को विश्वसनीय रखने के लिए कृपया अपना आवाज़ हस्ताक्षर ताज़ा करें।",
        speakPassphraseLabel: "पासफ़्रेज़ बोलें:",
        sessionReplacementRequired: "आवाज़ सफलतापूर्वक पंजीकृत की गई। कृपया लॉग आउट करें और आवाज़ प्रमाणीकरण सक्रिय करने के लिए फिर से आवाज़ के साथ साइन इन करें।",
        logoutRequired: "आप लॉग आउट हो रहे हैं। यह आपका एकमात्र विश्वसनीय उपकरण था। जारी रखने के लिए कृपया फिर से साइन इन करें।",
        logoutDueToDeviceChange: "आपके उपकरण बाइंडिंग को पासवर्ड से आवाज़ प्रमाणीकरण में बदल दिया गया है। सुरक्षा कारणों से, आपको लॉग आउट करना होगा और आवाज़ प्रमाणीकरण के साथ फिर से साइन इन करना होगा।",
        voiceBindingReplaced: "आपने अपनी आवाज़ बाइंडिंग अपडेट की है। सुरक्षा कारणों से, आपको अपने नए आवाज़ नमूने के साथ लॉग आउट करना होगा और फिर से साइन इन करना होगा।",
      },
      logOut: "लॉग आउट",
      back: "वापस",
      loadingAccountDetails: "खाता विवरण लोड कर रहे हैं…",
      showingAccounts: "दिखा रहे हैं 5 में से",
      accounts: "खाते।",
      hide: "छुपाएँ",
      show: "दिखाएँ",
      debitCards: "डेबिट कार्ड",
      creditCards: "क्रेडिट कार्ड",
      available: "उपलब्ध",
    },
    transactions: {
      title: "पूरा लेनदेन इतिहास",
      accounts: "खाते",
      selectAccount: "खाता चुनें",
      currentBalance: "वर्तमान शेष राशि:",
      transactions: "लेनदेन",
      noTransactionsFound: "इस खाते के लिए कोई लेनदेन नहीं मिला।",
      fetchingTransactions: "लेनदेन प्राप्त कर रहे हैं…",
      reference: "संदर्भ:",
      downloadStatement: "खाता स्टेटमेंट डाउनलोड करें",
      fromDate: "से तारीख",
      toDate: "तक तारीख",
      downloadStatementButton: "स्टेटमेंट डाउनलोड करें",
      preparing: "तैयार कर रहे हैं…",
      selectAccountToDownload: "स्टेटमेंट डाउनलोड करने के लिए एक खाता चुनें।",
      chooseBothDates: "दोनों से और तक की तारीखें चुनें।",
      startDateBeforeEnd: "शुरुआती तारीख अंतिम तारीख से पहले होनी चाहिए।",
      invalidDateRange: "अमान्य तारीख सीमा प्रदान की गई।",
      statementDownloaded: "स्टेटमेंट डाउनलोड किया गया",
      transaction: "लेनदेन के साथ।",
      mostRecent: "सबसे हालिया",
      transactionsLimit: "लेनदेन के साथ स्टेटमेंट डाउनलोड किया गया। पुरानी प्रविष्टियों के लिए, कृपया दूसरी अवधि डाउनलोड करें।",
      unableToDownload: "स्टेटमेंट डाउनलोड करने में असमर्थ।",
      rbiGuidelines: "RBI दिशानिर्देशों के अनुसार, डिजिटल स्टेटमेंट में 500 तक लेनदेन शामिल हैं। कृपया तारीख सीमा कम करें और पुनः प्रयास करें।",
      back: "वापस",
    },
    reminders: {
      title: "सभी अनुस्मारक",
      reminders: "अनुस्मारक",
      loading: "अनुस्मारक लोड कर रहे हैं…",
      noRemindersFound: "कोई अनुस्मारक नहीं मिला।",
      markSent: "भेजा गया चिह्नित करें",
      back: "वापस",
    },
    beneficiaries: {
      title: "लाभार्थी प्रबंधित करें",
      subtitle: "RBI उच्च-मूल्य ट्रांसफर से पहले एक सत्यापित लाभार्थी सूची अनिवार्य करता है। यहाँ विश्वसनीय प्राप्तकर्ता जोड़ें ताकि भविष्य के भुगतान तेज़ और सुरक्षित हों।",
      backToPrevious: "← पिछले पृष्ठ पर वापस",
      addNewBeneficiary: "एक नया लाभार्थी जोड़ें",
      beneficiaryName: "लाभार्थी नाम",
      beneficiaryNamePlaceholder: "उदा., रमेश कुमार",
      accountNumber: "खाता संख्या",
      accountNumberPlaceholder: "सटीक खाता संख्या दर्ज करें",
      bankName: "बैंक नाम",
      bankNamePlaceholder: "सन नेशनल बैंक",
      ifsc: "IFSC (वैकल्पिक)",
      ifscPlaceholder: "SUNB0001HYD",
      addBeneficiary: "लाभार्थी जोड़ें",
      adding: "जोड़ रहे हैं…",
      beneficiaryAdded: "लाभार्थी सफलतापूर्वक जोड़ा गया।",
      provideNameAndAccount: "कृपया एक लाभार्थी नाम और खाता संख्या प्रदान करें।",
      savedBeneficiaries: "सहेजे गए लाभार्थी",
      loading: "लाभार्थी लोड कर रहे हैं…",
      noBeneficiariesYet: "अभी तक कोई लाभार्थी नहीं जोड़ा गया।",
      addedOn: "जोड़ा गया",
      remove: "हटाएँ",
      removeConfirm: "यह तुरंत लाभार्थी को अक्षम कर देगा। क्या आप जारी रखना चाहते हैं?",
      productionNote: "प्रोडक्शन तैनाती एक लाभार्थी सक्रिय होने से पहले एक कूलिंग अवधि और OTP पुष्टि लागू करेगी।",
      logOut: "लॉग आउट",
    },
    deviceBinding: {
      title: "विश्वसनीय उपकरण और आवाज़ बाइंडिंग प्रबंधित करें",
      trustedDevices: "विश्वसनीय उपकरण",
      loading: "उपकरण बाइंडिंग लोड कर रहे हैं…",
      noDevices: "कोई विश्वसनीय उपकरण नहीं मिला। आवाज़ + उपकरण बाइंडिंग का आनंद लेने के लिए इस उपकरण को जोड़ें।",
      lastVerified: "अंतिम सत्यापित:",
      never: "कभी नहीं",
      revoke: "रद्द करें",
      revoked: "रद्द किया गया",
      bindDevice: "इस उपकरण को बाइंड करें",
      description: "आवाज़ + उपकरण बाइंडिंग RBI के जोखिम-आधारित प्रमाणीकरण मार्गदर्शन के अनुसार आपके आवाज़ हस्ताक्षर को इस उपकरण के साथ जोड़ती है। एक मित्रतापूर्ण लेबल प्रदान करें, फिर पासफ़्रेज़ बोलते हुए खुद को रिकॉर्ड करें ताकि हम इस उपकरण को सुरक्षित कर सकें।",
      deviceLabel: "उपकरण लेबल",
      deviceLabelPlaceholder: "उदा., अनन्या का रेडमी नोट",
      voicePassphrase: "आवाज़ पासफ़्रेज़",
      speakPassphrase: "सत्यापन के दौरान नीचे दिए गए पासफ़्रेज़ में से एक बोलें:",
      recordVoiceSample: "आवाज़ का नमूना रिकॉर्ड करें",
      stopRecording: "रिकॉर्डिंग रोकें",
      deviceFingerprint: "उपकरण फिंगरप्रिंट (हैश किया गया):",
      bindingDevice: "उपकरण बाइंड कर रहे हैं…",
      deviceBound: "उपकरण और आवाज़ पासफ़्रेज़ सफलतापूर्वक पंजीकृत किया गया।",
      deviceRevoked: "उपकरण बाइंडिंग सफलतापूर्वक रद्द की गई।",
      pleaseRecord: "कृपया पासफ़्रेज़ रिकॉर्ड करें",
      beforeBinding: "बाइंडिंग से पहले।",
      back: "वापस",
    },
    signInHelp: {
      title: "साइन इन करने में मदद चाहिए?",
      subtitle: "अपने पासवर्ड या आवाज़ के साथ ऑडियो OTP सुरक्षा का उपयोग करके अपने सन नेशनल बैंक प्रोफ़ाइल तक पहुंचने के लिए इन त्वरित चरणों का पालन करें।",
      passwordOtp: "पासवर्ड + OTP",
      step1: "बैंक द्वारा जारी किए गए ग्राहक उपयोगकर्ता आईडी को बिल्कुल दर्ज करें।",
      step2: "अपना पासवर्ड टाइप करें और दबाएं",
      step3: "सिस्टम आपके क्रेडेंशियल को सत्यापित करता है और फिर एक-बार पासवर्ड के लिए संकेत देता है।",
      step4: "प्रोटोटाइप OTP दर्ज करें",
      step4Note: "(प्रोडक्शन SMS/ईमेल/WhatsApp का उपयोग करेगा)।",
      step5: "साइन इन समाप्त करने के लिए सबमिट करें। गलत प्रविष्टियां सुरक्षा के लिए OTP चरण को रीसेट करती हैं।",
      voiceLoginOtp: "आवाज़ लॉगिन + OTP",
      voiceStep1: "लॉगिन स्क्रीन पर",
      voiceStep1Bold: "आवाज़",
      voiceStep1End: "टैब चुनें।",
      voiceStep2: "पहली बार के उपयोगकर्ताओं के लिए, अपने आवाज़ हस्ताक्षर को पंजीकृत करने के लिए पासफ़्रेज़ \"सन बैंक मेरा साथी, हर कदम सुरक्षित बैंकिंग का वादा\" को दो बार रिकॉर्ड करें।",
      voiceStep3: "वापसी करने वाले उपयोगकर्ता कोई भी स्पष्ट वाक्य बोल सकते हैं। 7-सेकंड कैप्चर विंडो के भीतर रहने के लिए ऑडियो मीटर देखें।",
      voiceStep4: "आवाज़ जांच पास होने के बाद, OTP दर्ज करें",
      voiceStep4End: "लॉगिन पूरा करने के लिए।",
      voiceTip: "सुझाव: सबसे अच्छी मिलान सटीकता के लिए एक शांत स्थान से रिकॉर्ड करें और माइक्रोफ़ोन को 10-15 सेमी दूर रखें।",
      stillCantSignIn: "अभी भी साइन इन नहीं कर सकते?",
      usePasswordMode: "यदि आपका आवाज़ नमूना उपलब्ध नहीं है तो पासवर्ड मोड का उपयोग करें।",
      clearBrowserCache: "डिवाइस बाइंडिंग को ताज़ा करने के लिए अपने ब्राउज़र कैश को साफ़ करें या निजी विंडो में पुनः प्रयास करें।",
      enableMicrophone: "सुनिश्चित करें कि इस साइट के लिए आपकी माइक्रोफ़ोन अनुमतियां सक्षम हैं।",
      contactSupport: "अपना पासवर्ड रीसेट करने या संदिग्ध उपकरण बाइंडिंग को रद्द करने के लिए शाखा सहायता से संपर्क करें।",
      goBack: "वापस जाएं",
      returnToLogin: "लॉगिन पर वापस जाएं",
      logIn: "लॉग इन करें",
    },
    chat: {
      handsFreeEnabled: "हैंड्स-फ्री सक्षम",
      backToProfile: "← प्रोफ़ाइल पर वापस जाएं",
      logOut: "लॉग आउट करें",
      uploadQRCode: "QR कोड अपलोड करें",
      assistantSpeaking: "सहायक बोल रहा है...",
      wasThisHelpful: "यह उत्तर कैसा था?",
      goodResponse: "अच्छा",
      badResponse: "बुरा",
      downloadStatement: "स्टेटमेंट डाउनलोड करें",
      downloadStatementTitle: "CSV के रूप में खाता स्टेटमेंट डाउनलोड करें",
    },
  },
};

/**
 * Get page strings for a specific language
 * @param {string} languageCode - Language code (e.g., 'en-IN', 'hi-IN')
 * @returns {object} Page strings for the specified language
 */
export const getPageStrings = (languageCode) => {
  return PAGE_STRINGS[languageCode] || PAGE_STRINGS[DEFAULT_LANGUAGE];
};

export default PAGE_STRINGS;

